"""init projects

Revision ID: 1eca776ad538
Revises: 
Create Date: 2023-06-26 18:08:20.907129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1eca776ad538"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
